"""auto update

Revision ID: 3b161ff45bcc
Revises: 
Create Date: 2026-06-03 22:31:16.942025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b161ff45bcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_my', sa.String(), nullable=True),
    sa.Column('title_zh', sa.String(), nullable=True),
    sa.Column('content_en', sa.String(), nullable=True),
    sa.Column('content_my', sa.String(), nullable=True),
    sa.Column('content_zh', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_id'), 'knowledge_articles', ['id'], unique=False)
    op.create_table('page_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_key', sa.String(), nullable=False),
    sa.Column('section_key', sa.String(), nullable=False),
    sa.Column('content_en', sa.String(), nullable=True),
    sa.Column('content_my', sa.String(), nullable=True),
    sa.Column('content_zh', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_contents_id'), 'page_contents', ['id'], unique=False)
    op.create_table('pig_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price_type', sa.String(), nullable=False),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.Column('price_per_head', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes_en', sa.String(), nullable=True),
    sa.Column('notes_my', sa.String(), nullable=True),
    sa.Column('notes_zh', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pig_prices_id'), 'pig_prices', ['id'], unique=False)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.String(), nullable=False),
    sa.Column('setting_value', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_pig_prices_id'), table_name='pig_prices')
    op.drop_table('pig_prices')
    op.drop_index(op.f('ix_page_contents_id'), table_name='page_contents')
    op.drop_table('page_contents')
    op.drop_index(op.f('ix_knowledge_articles_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    # ### end Alembic commands ###